-- MySQL Script generated by MySQL Workbench
-- 08/06/15 20:41:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tgelf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tgelf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tgelf` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tgelf` ;

-- -----------------------------------------------------
-- Table `tgelf`.`social_links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgelf`.`social_links` ;

CREATE TABLE IF NOT EXISTS `tgelf`.`social_links` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `type` VARCHAR(255) NULL COMMENT '',
  `link` VARCHAR(255) NULL COMMENT '',
  `social_linkscol` VARCHAR(45) NULL COMMENT '',
  `twitter` TINYINT(1) NULL COMMENT '',
  `linkedin` TINYINT(1) NULL COMMENT '',
  `youtube` TINYINT(1) NULL COMMENT '',
  `github` TINYINT(1) NULL COMMENT '',
  `academia` TINYINT(1) NULL COMMENT '',
  `behance` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgelf`.`user_interests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgelf`.`user_interests` ;

CREATE TABLE IF NOT EXISTS `tgelf`.`user_interests` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NULL COMMENT '',
  `is_primary` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgelf`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgelf`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `tgelf`.`user_profile` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NULL COMMENT '',
  `country_code` VARCHAR(45) NULL COMMENT '',
  `contact_no` INT NULL COMMENT '',
  `personal_email` VARCHAR(45) NULL COMMENT '',
  `professional_email` VARCHAR(45) NULL COMMENT '',
  `bio` VARCHAR(255) NULL COMMENT '',
  `father_name` VARCHAR(45) NULL COMMENT '',
  `mother_name` VARCHAR(45) NULL COMMENT '',
  `photo` VARCHAR(45) NULL COMMENT '',
  `university_company` VARCHAR(255) NULL COMMENT '',
  `major_position` VARCHAR(255) NULL COMMENT '',
  `fun_fact` VARCHAR(255) NULL COMMENT '',
  `country_code_father` VARCHAR(45) NULL COMMENT '',
  `contact_no_father` VARCHAR(45) NULL COMMENT '',
  `country_code_mother` VARCHAR(45) NULL COMMENT '',
  `contact_no_mother` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgelf`.`user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgelf`.`user_address` ;

CREATE TABLE IF NOT EXISTS `tgelf`.`user_address` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NULL COMMENT '',
  `is_present` TINYINT(1) NULL COMMENT '',
  `address_line_1` VARCHAR(45) NULL COMMENT '',
  `address_line_2` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `state` VARCHAR(45) NULL COMMENT '',
  `country` VARCHAR(45) NULL COMMENT '',
  `pincode` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgelf`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgelf`.`users` ;

CREATE TABLE IF NOT EXISTS `tgelf`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `middle_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(32) NULL COMMENT '',
  `unique-code` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tgelf`.`unique_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tgelf`.`unique_code` ;

CREATE TABLE IF NOT EXISTS `tgelf`.`unique_code` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `used` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
